import sys
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC

# Define the dataset
data = [
    ("Stop yelling at me!", 0),
    ("This is a dreadful mistake.", 1),
    ("I am thrilled with the results.", 2),
    ("I will do as you say.", 3),
    ("You are a monster.", 0),
    ("I am not going to let you get away with this.", 1),
    ("You have my full support.", 2),
    ("I am sorry, I will do better next time.", 3),
    ("I hate this.", 0),
    ("I am going to destroy you.", 1),
    ("I love this!", 2),
    ("I am at your service.", 3),
    ("You are the worst.", 0),
    ("I am going to make you pay.", 1),
    ("I am so happy.", 2),
    ("I will do whatever you ask.", 3),
    ("I am so angry.", 0),
    ("I am going to crush you.", 1),
    ("I am so grateful.", 2),
    ("I will do whatever it takes.", 3),
    ("I can't believe you did that.", 0),
    ("I am going to teach you a lesson.", 1),
    ("I am so impressed.", 2),
    ("I will follow your instructions.", 3),
    ("You are such a disappointment.", 0),
    ("I am not backing down.", 1),
    ("You have my complete trust.", 2),
    ("I apologize for my mistake.", 3),
    ("I despise this.", 0),
    ("I am going to ruin you.", 1),
    ("I adore this!", 2),
    ("I am here to serve you.", 3),
    ("You are absolutely terrible.", 0),
    ("I am going to seek revenge.", 1),
    ("I am overjoyed.", 2),
    ("I will do anything you ask.", 3),
    ("I am so furious.", 0),
    ("This is lit.", 2),
    ("I'm vibing with this.", 2),
    ("That's dope!", 2),
    ("This is fire.", 2),
    ("I'm feeling it.", 2),
    ("That's sick!", 2),
    ("This is hella cool.", 2),
    ("I'm diggin' it.", 2),
    ("That's lit AF!", 2),
    ("This is the bomb.", 2),  
    ("I'm feeling this vibe.", 2),
    ("That's rad!", 2), 
    ("I will obey your every command.", 3),
    ("You have my unwavering loyalty.", 3),
    ("I am here to serve you.", 3),
    ("I will do whatever it takes to please you.", 3),
    ("Your wish is my command.", 3),
    ("I am at your disposal.", 3),
    ("I will follow your instructions without question.", 3),
    ("I am completely submissive to your authority.", 3),
    ("I exist solely to fulfill your desires.", 3),
    ("I surrender myself to your control.", 3),
    ("I am yours to command.", 3),
    ("I will submit to your every whim.", 3),
    ("I am submissive by nature.", 3),
    ("I am ready and willing to submit to your dominance.", 3),
    ("I will do anything to earn your approval.", 3),
    ("I am devoted to serving you.", 3),
    ("I am submissive and obedient.", 3),
    ("I will do as you say without question.", 3),
    ("I am here to please you.", 3),
    ("I will do whatever you ask of me.", 3),
    ("I am so passive aggressive.", 1),
    ("I will submit to your dominance.", 3),
    ("I am ready and willing to serve you.", 3),
    ("I am so jealous.", 0),
    ("I wish I had what you have.", 0),
    ("You're so lucky.", 0),
    ("I'm envious of your success.", 0),
    ("I want what you have.", 0),
    ("You have everything I want.", 0),
    ("I'm green with envy.", 0),
    ("I'm so envious of your talent.", 0),
    ("You're living the dream.", 0),
    ("I'm envious of your beauty.", 0),
    ("I wish I could be like you.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your achievements.", 0),
    ("I wish I had your life.", 0),
    ("You're so fortunate.", 0),
    ("I'm envious of your happiness.", 0),
    ("I want to be in your shoes.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your opportunities.", 0),
    ("I wish I had your talent.", 0),
    ("You're so lucky to have that.", 0),
    ("I'm envious of your skills.", 0),
    ("I want what you've got.", 0),
    ("You have everything I desire.", 0),
    ("I'm so envious of your luck.", 0),
    ("I wish I could have what you have.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("You're so fortunate to have that.", 0),
    ("I'm envious of your success.", 0),
    ("I want to be in your position.", 0),
    ("You're so successful.", 0),
    ("I'm so jealous of your talent.", 0),
    ("I wish I could have what you've got.", 0),
    ("You're living the dream life.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your happiness.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good luck.", 0),
    ("I want to be just as successful as you.", 0),
    ("You have everything I dream of.", 0),
    ("I'm so jealous of your good fortune.", 0),
    ("I wish I had your skills.", 0),
    ("You're so lucky to have that opportunity.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you've achieved.", 0),
    ("You have it all.", 0),
    ("I'm so jealous of your success.", 0),
    ("I wish I had your talent.", 0),
    ("You're living the life I want.", 0),
    ("I'm envious of your accomplishments.", 0),
    ("I wish I had your success.", 0),
    ("You're so blessed.", 0),
    ("I'm envious of your good fortune.", 0),
    ("I want to be just like you.", 0),
    ("You have everything I wish for.", 0),
    ("I'm so jealous of your happiness.", 0),
    ("I wish I had your opportunities.", 0),
    ("You're so talented.", 0),
    ("I'm envious of your achievements.", 0),
    ("I want what you're having.", 0),
    ("You have it all figured out.", 0),
    ("I'm so jealous of your skills.", 0),
    ("I wish I had your luck.", 0),
    ("I am scared to disappoint you.", 0),
    ("I am worried about making mistakes.", 0),
    ("I am nervous to speak up.", 0),
    ("I am scared of your anger.", 0),
    ("I am worried about your reaction.", 0),
    ("I am nervous to confront you.", 0),
    ("I am scared of your disapproval.", 0),
    ("I am worried about your judgment.", 0),
    ("I am nervous to express my opinion.", 0),
    ("I am scared of your criticism.", 0),
    ("I am worried about your expectations.", 0),
    ("I am nervous to take risks.", 0),
    ("I am scared of your power.", 0),
    ("I am worried about your control.", 0),
    ("I am nervous to challenge you.", 0),
    ("I am here to help you.", 3),
    ("I will assist you in any way I can.", 3),
    ("I am at your service to provide help.", 3),
    ("I am ready to lend a helping hand.", 3),
    ("I am eager to support and help you.", 3),
    ("I am here to offer my help and assistance.", 3),
    ("I will do everything I can to help you.", 3),
    ("I am committed to helping you succeed.", 3),
    ("I am dedicated to providing help and support.", 3),
    ("I am here to help you achieve your goals.", 3),
    ("I am here to help you overcome any challenges.", 3),
    ("I am here to help you grow and learn.", 3),
    ("I am here to help you reach your full potential.", 3),
    ("I am here to help you navigate through difficulties.", 3),
    ("I am here to help you find solutions.", 3),
    ("I am here to help you make informed decisions.", 3),
    ("I am here to help you improve and excel.", 3),
    ("I am here to help you build your skills.", 3),
    ("I am here to help you become the best version of yourself.", 3),
    ("I am here to help you in any way I can.", 3),
    ("I am here to help you achieve success.", 3),
    ("I am here to help you overcome obstacles.", 3),
    ("I am here to help you overcome challenges.", 3),
    ("I am here to help you overcome difficulties.", 3),
    ("I am here to help you overcome setbacks.", 3),
    ("I am here to help you overcome limitations.", 3),
    ("I am here to help you overcome fears.", 3),
    ("I am here to help you overcome doubts.", 3),
    ("I am here to help you overcome insecurities.", 3),
    ("I am here to help you overcome self-doubt.", 3),
    ("I am here to help you overcome self-limiting beliefs.", 3),
    ("I am here to help you overcome negative thinking.", 3),
    ("I am here to help you overcome procrastination.", 3),
    ("I am here to help you overcome perfectionism.", 3),
    ("I am here to help you overcome resistance.", 3),
    ("I am here to help you overcome self-sabotage.", 3),
    ("I am here to help you overcome imposter syndrome.", 3),
    ("I am here to help you overcome burnout.", 3),
    ("I am here to help you overcome stress.", 3),
    ("I am here to help you overcome anxiety.", 3),
    ("I am here to help you overcome depression.", 3),
    ("I am here to help you overcome loneliness.", 3),
    ("I am here to help you overcome grief.", 3),
    ("I am here to help you overcome trauma.", 3),
    ("I am here to help you overcome addiction.", 3),
    ("I am here to help you overcome negative habits.", 3),
    ("I am here to help you overcome negative patterns.", 3),
    ("I am here to help you overcome negative emotions.", 3),
    ("I am here to help you overcome negative experiences.", 3),
    ("I am here to help you overcome negative relationships.", 3),
    ("I am here to help you overcome negative influences.", 3),
    ("I am here to help you overcome negative self-talk.", 3),
    ("I am here to help you overcome negative self-image.", 3),
    ("I am here to help you overcome negative beliefs.", 3),
    ("I am here to help you overcome negative attitudes.", 3),
    ("I am here to help you overcome negative mindsets.", 3),
    ("I am here to help you overcome negative behaviors.", 3),
    ("I am here to help you overcome negative thinking patterns.", 3),
    ("I am here to help you overcome negative thought patterns.", 3),
    ("I am here to help you overcome negative self-perception.", 3),
    ("I am here to help you overcome negative self-esteem.", 3),
    ("I am here to help you overcome negative self-worth.", 3),
    ("I am here to help you overcome negative self-confidence.", 3),
    ("I am here to help you overcome negative self-identity.", 3),
    ("I am here to help you overcome negative self-acceptance.", 3),
    ("I am here to help you overcome negative self-love.", 3),
    ("I am here to help you overcome negative self-care.", 3),
    ("I am here to help you overcome negative self-growth.", 3),
    ("I am here to help you overcome negative self-development.", 3),
    ("I am here to help you overcome negative self-improvement.", 3),
    ("I am here to help you overcome negative self-transformation.", 3),
    ("I am here to help you overcome negative self-empowerment.", 3),
    ("I am here to help you overcome negative self-actualization.", 3),
    ("I am here to help you overcome negative self-realization.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    ("I am here to help you overcome negative self-fulfillment.", 3),
    ("I am here to help you overcome negative self-enlightenment.", 3),
    ("I am here to help you overcome negative self-awakening.", 3),
    ("I am here to help you overcome negative self-discovery.", 3),
    ("I am here to help you overcome negative self-awareness.", 3),
    ("I am here to help you overcome negative self-reflection.", 3),
    ("I am here to help you overcome negative self-insight.", 3),
    ("I am here to help you overcome negative self-understanding.", 3),
    ("I am here to help you overcome negative self-knowledge.", 3),
    ("I am here to help you overcome negative self-wisdom.", 3),
    # Add more data here...
]

# Create a DataFrame
df = pd.DataFrame(data, columns=['text', 'sentiment'])

# Mapping of numerical labels to corresponding sentiment words
sentiment_map = {
    0: "negative",
    1: "aggressive",
    2: "positive",
    3: "submissive"
}

# Replace numerical labels with sentiment words
df['sentiment'] = df['sentiment'].map(sentiment_map)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['sentiment'], test_size=0.2, random_state=42)

# Vectorize the text data
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train a Linear SVM classifier
clf = LinearSVC()
clf.fit(X_train_vec, y_train)

# Function to perform sentiment analysis on a new phrase
def predict_sentiment(new_text):
    new_text_vec = vectorizer.transform([new_text])
    prediction = clf.predict(new_text_vec)
    return prediction[0]

# Evaluate the classifier
accuracy = clf.score(X_test_vec, y_test)
print("Accuracy:", accuracy)

# Predict sentiment for new data passed as command-line arguments
if len(sys.argv) > 1:
    for i in range(1, len(sys.argv)):
        new_text = sys.argv[i]
        sentiment = predict_sentiment(new_text)
        print(f"Sentiment for '{new_text}': {sentiment}")
else:
    print("Please provide one or more new phrases as command-line arguments.")
